name: Makefile CI
  
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .gitignore
      - .gitattribues
      - README.md
      - LICENSE
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - .gitignore
      - .gitattribues
      - README.md
      - LICENSE

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name:  build linux
      run: |
       chmod +x ./main_run_build_script.sh
       ./main_run_build_script.sh build-linux
